config/routes.rb
Rails.application.routes.draw do
  root 'redesign#index'

  # Home page
  get '/home', to: 'redesign#index'

  # Old design
  get '/old_design', to: 'home_page#index'

  # Password reset
  get 'password_resets/new'
  get 'password_resets/edit'

  # Session
  get 'sessions/new'
  # get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  get '/reset-password', to: 'redesign#index'

  # Cart products
  post 'add_product', to: 'cart_products#create'
  delete 'delete_product', to: 'cart_products#destroy'

  # Cart
  get '/cart', to: 'redesign#index'

  # User

  # Admin
  get '/admin', to: 'admin#index'

  # Order products
  get 'order_products/index'

  # resources :users, only: %i[create new show edit update]
  # resources :carts, only: %i[show]
  # resources :account_activations, only: :edit
  # resources :password_resets, only: %i[new create edit update]
  # resources :orders, only: %i[new create]
  resources :order_products, only: :index

  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :products, only: %i[new create show]
    resources :orders, only: %i[index update]
  end

  get 'orders/:id', to: 'redesign#index'
  get '/login', to: 'redesign#index'
  get '/register', to: 'redesign#index'

  get 'password-update/:id', to: 'redesign#index'
  get '/my-orders', to: 'redesign#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: %i[index]
      resources :users, only: %i[show create] do
        get '/current_user', action: :show, on: :collection
        get '/orders', action: :orders, on: :collection
      end

      resources :categories, only: %i[index]

      resources :cart_products, only: %i[create index destroy]

      patch '/empty_cart/:id', to: 'cart_products#empty_cart'

      resources :orders, only: %i[show create]

      resources :confirm_email, only: %i[show] do
        get '/:activation_token', action: :show, on: :collection
      end

      resources :sessions, only: %i[create destroy] do
        delete '/', action: :destroy, on: :collection
      end

      resources :reset_password, only: %i[create update]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  before_destroy :remove_orders
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: UsersHelper::VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password
  has_one :cart, dependent: :destroy
  has_many :orders

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def session_token
    remember_digest || remember
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def remove_orders
      Order.where(user_id: id).destroy_all
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to admin_users_url
  end
end

app/controllers/api/v1/users_controller.rb

class Api::V1::UsersController < ApplicationController
  before_action :logged_in_user, only: %i[orders]
  skip_before_action :verify_authenticity_token

  def show
    if current_user.nil?
      render json: { message: 'Please log in' }, status: 401
    else
      render json: current_user, serializer: UserSerializer
    end
  end

  def orders
    data = {
      handled: ActiveModelSerializers::SerializableResource.new(current_user.orders.where(handled: true), each_serializer: OrderSerializer),
      unhandled: ActiveModelSerializers::SerializableResource.new(current_user.orders.where(handled: false), each_serializer: OrderSerializer)
    }
    render json: data
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      @user.send_activation_email
      render json: @user
    else
      render json: { message: 'Invalid data' }, status: :bad_request
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy show]
  before_action :authenticate_user, only: %i[edit update show]

  def new
    @user = User.new
    @disable_nav = true
    @disable_footer = true
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_url
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  def create_cart_for_user(user)
    cart = Cart.new
    user.cart = cart
  end

  def no_of_products(product)
    CartProduct.find_by(cart_id: current_user.cart.id, product_id: product.id).quantity
  end

  def delete_user_order(user)
    CartProduct.where(cart_id: user.cart.id).delete_all
  end
end

app/views/users/edit.html.haml
= provide(:title, "Edit user")

.form
  .form-container
    %p Update your profile
    = form_with(model: @user, local: true) do |f|
      .fields
        .form-group
          = f.label :name
          = f.text_field :name, class: 'field'
        .form-group
          = f.label :email
          = f.email_field :email, class: 'field'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'field'
        .form-group
          = f.label :password_confirmation, 'Confirmation'
          = f.password_field :passowrd_confirmation, class: 'field last-border'
        = f.submit "Save changes", class: 'btn btn-primary'

app/views/users/new.html.haml
= provide(:title, "Sign Up")
.signup-form
  .form-content
    .header
      .hero
        = link_to root_url do
          = image_tag "logo.svg"
        %p Sign up today
    .options-wrapper
      .options
        = link_to '/login' do
          %p Log in
        = link_to '#' do
          %p Sign up
    = form_with(model: @user, local: true) do |f|
      .fields
        .form-group
          = f.label :name
          = f.text_field :name, class: "field"
        .form-group
          = f.label :email
          = f.email_field :email, class: "field"
        .form-group
          = f.label :password
          = f.password_field :password, class: "field"
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: "field"
        .actions
          = f.submit "Sign Up", class: "btn btn-primary"

app/views/users/show.html.haml
.user-container
  .user-content
    - if Order.where(user_id: @user.id).count == 0
      .illustration
        = image_tag 'no_order.svg'
        .info
          %span You have not placed any order yet
          = link_to 'Place an order now!', root_url
    - else
      .orders-wrapper
        .pending
          %p.order= "Pending orders (#{Order.order_count(@user.id, false)})"
          - @user.orders.where.not(handled: true).each do |order|
            = link_to order_path(order) do
              .orders
                .order-number= "Order ##{order.id}"
                .order-total= "Total: $ #{OrderProduct.total_sum(order.id)}"
                .order-date= order.placed_at.strftime("%m/%d at: %H:%M")
        .handled
          %p.order= "Completed orders (#{Order.order_count(@user.id, true)})"
          - @user.orders.where(handled: true).each do |order|
            = link_to order_path(order) do
              .orders
                .order-number= "Order ##{order.id}"
                .order-total= "Total: $ #{OrderProduct.total_sum(order.id)}"
                .order-date= order.placed_at.strftime("%m/%d at: %H:%M")