config/routes.rb
Rails.application.routes.draw do
  root 'redesign#index'

  # Home page
  get '/home', to: 'redesign#index'

  # Old design
  get '/old_design', to: 'home_page#index'

  # Password reset
  get 'password_resets/new'
  get 'password_resets/edit'

  # Session
  get 'sessions/new'
  # get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  get '/reset-password', to: 'redesign#index'

  # Cart products
  post 'add_product', to: 'cart_products#create'
  delete 'delete_product', to: 'cart_products#destroy'

  # Cart
  get '/cart', to: 'redesign#index'

  # User

  # Admin
  get '/admin', to: 'admin#index'

  # Order products
  get 'order_products/index'

  # resources :users, only: %i[create new show edit update]
  # resources :carts, only: %i[show]
  # resources :account_activations, only: :edit
  # resources :password_resets, only: %i[new create edit update]
  # resources :orders, only: %i[new create]
  resources :order_products, only: :index

  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :products, only: %i[new create show]
    resources :orders, only: %i[index update]
  end

  get 'orders/:id', to: 'redesign#index'
  get '/login', to: 'redesign#index'
  get '/register', to: 'redesign#index'

  get 'password-update/:id', to: 'redesign#index'
  get '/my-orders', to: 'redesign#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: %i[index]
      resources :users, only: %i[show create] do
        get '/current_user', action: :show, on: :collection
        get '/orders', action: :orders, on: :collection
      end

      resources :categories, only: %i[index]

      resources :cart_products, only: %i[create index destroy]

      patch '/empty_cart/:id', to: 'cart_products#empty_cart'

      resources :orders, only: %i[show create]

      resources :confirm_email, only: %i[show] do
        get '/:activation_token', action: :show, on: :collection
      end

      resources :sessions, only: %i[create destroy] do
        delete '/', action: :destroy, on: :collection
      end

      resources :reset_password, only: %i[create update]
    end
  end
end

app/views/shared/_dashboard.html.haml
.dashboard-container
  .top-container
    %header
      = link_to root_url do
        .header-content
          = image_tag 'dashboard/logo.png'
          .logo-text
            %div EUREKA
            %div CAFFE
    .heading RESOURCES
    .routes-container
      = link_to admin_users_path do
        %div{ class: "#{active_dashboard(admin_users_path)}" }
          = image_tag 'dashboard/user.svg'
          %div USERS
      = link_to admin_orders_path do
        %div{ class: "#{active_dashboard(admin_orders_path)}"}
          = image_tag 'dashboard/order.svg'
          %div ORDERS
      = link_to new_admin_product_path do
        %div{ class: "#{active_dashboard(new_admin_product_path)}"}
          = image_tag 'dashboard/add_product.svg'
          %div ADD PRODUCT
  .bottom-container
    .heading EXTRA
    .routes-container
      = link_to root_url(preview: User.digest('1')) do
        .route
          = image_tag 'dashboard/preview.svg'
          %div PREVIEW
      = link_to logout_url, method: :delete do
        .route
          = image_tag 'dashboard/logout.svg'
          %div LOGOUT
    .profile-wrapper
      .profile
        = image_tag 'dashboard/avatar.svg'
        .profile-info
          .name= current_user.name
          .status ONLINE

app/views/shared/_footer.html.haml
%footer 
  .footer-wrapper
    %nav
      = link_to :root do
        = image_tag "logo_footer.png"
      %ul
        %li
          %a{href: "#"} HOME
        %li
          %a{href: "#"} ABOUT
        %li
          %a{href: "#"} SERVICE
        %li
          %a{href: "#"} BLOG
        %li
          %a{href: "#"} CONTACTS      
    %hr
    .social-links
      %p Copyright © 2009 - 2014 - Aliquam cursus massa quis vestibulum porta 
      .media
        = image_tag "fb.png"
        = image_tag "twitter.png"
        = image_tag "linkedin.png"

app/views/shared/_navbar.html.haml
%header{class: "#{current_request?(controller: 'home_page', action: "index") ? 'navbar-absolute' : 'navbar'}"}
  = link_to :root do
    .logo-container
      .logo-mark
        = image_tag "logo.svg"
      .logo-text
        %div#eureka EUREKA
        %div#caffe CAFFE
  %nav
    %ul
      %li
        %a{href: root_url, class: "#{active_class(root_url)}"} HOME
      %li
        %a{href: "#"} ABOUT
      %li
        %a{href: "#"} SERVICE
      %li
        %a{href: "#"} BLOG
      %li
        %a{href: "#"} CONTACTS
    - if logged_in?
      = link_to user_path(current_user) do
        %p.current-user= current_user.name
    .dropdown
      - if logged_in?
        .dropdown-menu
          = link_to 'Logout', '/logout', method: :delete, class: 'dropdown-item'
          = link_to 'Settings', edit_user_path(current_user), class: 'dropdown-item'
          = link_to 'Switch account', logout_path(switch: 1), method: :delete, class: 'dropdown-item'
        = image_tag "user.svg", "data-toggle": "dropdown", "aria-expanded": "false", "aria-haspopup": "true", class: 'user'
        - if current_user != nil && current_user.cart.products.count > 0 && !current_page?('/cart')
          = link_to '/cart' do
            = image_tag 'cart.svg',class: 'cart-notify'
            %span.badge= CartProduct.no_of_products(current_user.cart)
        - else
          = link_to image_tag("cart.svg"), cart_path(current_user.cart), class: 'cart'
      - else
        = image_tag "user.svg", "data-toggle": "dropdown", "aria-expanded": "false", "aria-haspopup": "true", class: 'guest'
        .dropdown-menu
          = link_to 'Log in', '/login', class: 'dropdown-item'
          = link_to "Sign up", '/signup', class: 'dropdown-item'