config/routes.rb
Rails.application.routes.draw do
  root 'redesign#index'

  # Home page
  get '/home', to: 'redesign#index'

  # Old design
  get '/old_design', to: 'home_page#index'

  # Password reset
  get 'password_resets/new'
  get 'password_resets/edit'

  # Session
  get 'sessions/new'
  # get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  get '/reset-password', to: 'redesign#index'

  # Cart products
  post 'add_product', to: 'cart_products#create'
  delete 'delete_product', to: 'cart_products#destroy'

  # Cart
  get '/cart', to: 'redesign#index'

  # User

  # Admin
  get '/admin', to: 'admin#index'

  # Order products
  get 'order_products/index'

  # resources :users, only: %i[create new show edit update]
  # resources :carts, only: %i[show]
  # resources :account_activations, only: :edit
  # resources :password_resets, only: %i[new create edit update]
  # resources :orders, only: %i[new create]
  resources :order_products, only: :index

  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :products, only: %i[new create show]
    resources :orders, only: %i[index update]
  end

  get 'orders/:id', to: 'redesign#index'
  get '/login', to: 'redesign#index'
  get '/register', to: 'redesign#index'

  get 'password-update/:id', to: 'redesign#index'
  get '/my-orders', to: 'redesign#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: %i[index]
      resources :users, only: %i[show create] do
        get '/current_user', action: :show, on: :collection
        get '/orders', action: :orders, on: :collection
      end

      resources :categories, only: %i[index]

      resources :cart_products, only: %i[create index destroy]

      patch '/empty_cart/:id', to: 'cart_products#empty_cart'

      resources :orders, only: %i[show create]

      resources :confirm_email, only: %i[show] do
        get '/:activation_token', action: :show, on: :collection
      end

      resources :sessions, only: %i[create destroy] do
        delete '/', action: :destroy, on: :collection
      end

      resources :reset_password, only: %i[create update]
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :logged_in_user, only: :show

  def index
    @carts = Cart.all
  end

  def show
    @cart = current_user.cart
  end
end

app/views/carts/show.html.haml
= provide(:title, 'Cart')
- if @cart.products.count != 0
  .cart-page
    .cart-page-wrapper
      .cart-container
        %header
          .header-left
            %p QTY
            %p ITEM
          .header-right
            %p PRICE
        .products-container
          - @cart.products.uniq.each do |product|
            .product-wrapper
              .product-left
                = link_to delete_product_path(id: product.id, cart: current_user.cart), method: :delete do
                  = image_tag 'minus.svg', class: 'delete-one'
                %p.quantity= no_of_products(product)
                = link_to add_product_path(route: 'cart', id: product.id, cart: current_user.cart), method: :post do
                  = image_tag 'plus.svg', class: 'add-one'
                %p.tite= product.title
              .product-right
                %p.price= "$ #{product.price}"
          .cart-footer
            .total
              %p Total:
              #total-sum= "$ #{CartProduct.total_sum(current_user.cart.id)}"
            = link_to 'CHECKOUT', new_order_path, class: 'btn btn-primary'
      = image_tag 'cart-illustration.png'
- else
  .empty-wrapper
    .empty-container
      = image_tag 'empty_cart.png'
      %h1 Empty Cart
      %p Look like you haven't made your choice yet...
      = link_to 'Back to menu', root_path, class: 'btn btn-primary'